### ISSUE TITLE
EEGLAB error in function pop_resample() at line 224 

### ISSUE THREAD

**Issue by drowning-in-codes** [amisepa/import_edf#4]
### Description
Hi,I'm new to eeg research and currently dealing with dataset [https://physionet.org/content/eegmmidb/1.0.0/](https://physionet.org/content/eegmmidb/1.0.0/), and I've seen issue [sccn/eeglab/issues/255](https://github.com/sccn/eeglab/issues/255) which is about importing dataset with extension import edf to deal with annotation and event. But after importing dataset by import edf and then when I changed the sampleing rate,error below occurs.
![image](https://user-images.githubusercontent.com/60743790/225184086-5c733623-b8e5-42d2-88f7-46a305fa9574.png)
if import dataset with function pop_biosig(), this kind of error doesn't happen. But event types and locations would load failed which I don't know why.
### **Example.**
**if I use function pop_biosig()**, channel location would load failed  and the information is blank.
![image](https://user-images.githubusercontent.com/60743790/225185822-a552cbb0-5d1f-4b56-9295-a111fad609dd.png)
the same is the avent types,because these types should be T0,T1,T2 according to the  [offcial websist](https://physionet.org/content/eegmmidb/1.0.0/).
![image](https://user-images.githubusercontent.com/60743790/225185775-eac9c3db-0d33-4f2c-bbd1-32dca1b54837.png)

**if I use function import_edf()**, channel location would load successfully,.
![image](https://user-images.githubusercontent.com/60743790/225186474-2cd48aed-7530-4864-a249-36b08be9abaa.png)
 and event types are T0,T1,T2 which means the extension works well.
![image](https://user-images.githubusercontent.com/60743790/225186577-65439d03-f079-46fd-a822-78befde227eb.png)

I wonder how to deal with this problem, thanks in advance!
### Steps to Reproduce
1. File> Import data> Using EEGLAB functions and plugins> from EDF/EDF+ files(using MATLAB edfread) ==> then select S001 folder then S001R07
![image](https://user-images.githubusercontent.com/60743790/225185211-2a12814d-3272-43ee-855e-4dbcac8d478d.png)

2. Tools->change sampling rate

### Env
Versions | OS version | [Windows 10 ] | | Matlab version | [(R2021b) ] | | EEGLAB version | V2022.1] 

Thanks again for your selfless help and useful tool

**Comment by amisepa** [comment]
Hi,

Sorry about the errors you're getting. Here are some suggestions:

Biosig plugin: 
Have you tried the different parameters of the Biosig toolbox? have you looked at the help bdf2biosig_events ?
Try to check, uncheck boxes, and see if that solves it. 

import_edf plugin:
I'm not getting the resampling error with one of my edf files, but I am getting it for the file you are trying to work with. This issue is with pop_resample , I'll see if I can find what's going on. 

When I try to import it into BDFReader, I get this error, suggesting something might be wrong with this file.
![Untitled](https://user-images.githubusercontent.com/58382227/225433588-759b5100-bbec-4441-a73d-2bb23aa70ebc.png)

Cedric

**Comment by amisepa** [comment]
I think I fixed the issue. Install this version here: https://github.com/amisepa/import_edf.git
replace the "import_edf" folder in eeglab > plugins with this one.
Test and let me know.

**Comment by drowning-in-codes** [comment]
Sorry for late reply. For Biosig plugin,I've tried to check and uncheck boxes in the pop-up window but it still doesn't work. And for "import_edf", it turns out that the extension downloaded from EEGLAB is out of date and I replace the import_edf file. It works well eventually. Thanks for your continuous help.  I will close this issue later if no other problems occurs.

**Comment by amisepa** [comment]
Ok, good to know it still didn't work with the biosig toolbox.

Yes, that's because I just fixed it and I need to submit a new version to eeglab, it's a process. 

Glad it's working now.

Cedric
